[tool.poetry]
name = "movement-cli-e2e-tests"
version = "0.1.0"
description = "Movement CLI E2E tests"
authors = ["Movment Labs <tony@movementlabs.xyz>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.7 <4"
aptos-sdk = "^0.5.1"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
